[build]
  # Répertoire de build (frontend)
  publish = "src/frontend/build"
  
  # Commande de build complète (frontend + backend + fonctions)
  command = "cd src/frontend && npm install && npm run build && cd ../.. && pip install -r requirements.txt && cd netlify/functions && npm install"

[build.environment]
  # Version de Node.js compatible avec Vite
  NODE_VERSION = "20"
  
  # Version de Python
  PYTHON_VERSION = "3.11"
  
  # Variables d'environnement
  NPM_FLAGS = "--production=false"

# Redirections pour API et SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les fonctions Netlify
[functions]
  directory = "netlify/functions"
