services:
  - type: web
    name: all-ai-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python start_server.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: NODE_VERSION
        value: 18
      - key: ALL_AI_SECRET_KEY
        value: your-secret-key-change-in-production-12345
      - key: ALL_AI_SUPERUSER
        value: admin
      - key: ALL_AI_SUPERUSER_PASSWORD
        value: admin123
      - key: ALL_AI_CORS_ORIGINS
        value: https://all-ai-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: all-ai-database
          property: connectionString
      - key: ALL_AI_LOG_LEVEL
        value: INFO
      - key: ALL_AI_HOST
        value: 0.0.0.0
      - key: ALL_AI_PORT
        value: $PORT
      - key: ALL_AI_STATIC_FILES_PATH
        value: src/frontend/build

databases:
  - name: all-ai-database
    databaseName: allai
    user: allai
    plan: free