services:
  - type: web
    name: all-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ALL_AI_SECRET_KEY
        value: your-secret-key-change-in-production-12345
      - key: ALL_AI_SUPERUSER
        value: admin
      - key: ALL_AI_SUPERUSER_PASSWORD
        value: admin123
      - key: ALL_AI_CORS_ORIGINS
        value: https://all-ai-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: all-ai-database
          property: connectionString
      - key: ALL_AI_LOG_LEVEL
        value: INFO
      - key: ALL_AI_HOST
        value: 0.0.0.0
      - key: ALL_AI_PORT
        value: $PORT

  - type: web
    name: all-ai-frontend
    env: static
    buildCommand: cd src/frontend && npm install && npm run build
    staticPublishPath: src/frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://all-ai-backend.onrender.com/api/$1
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: all-ai-database
    databaseName: allai
    user: allai
    plan: free