services:
  - type: web
    name: langflow-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start-simple.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: LANGFLOW_SECRET_KEY
        value: your-secret-key-change-in-production-12345
      - key: LANGFLOW_SUPERUSER
        value: admin
      - key: LANGFLOW_SUPERUSER_PASSWORD
        value: admin123
      - key: LANGFLOW_CORS_ORIGINS
        value: https://langflow-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: langflow-database
          property: connectionString
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        value: $PORT
      - key: LANGFLOW_AUTO_LOGIN
        value: "true"
      - key: LANGFLOW_BACKEND_ONLY
        value: "true"
      - key: LANGFLOW_DATABASE_URL
        fromDatabase:
          name: langflow-database
          property: connectionString
      - key: LANGFLOW_CACHE_TYPE
        value: "InMemoryCache"
      - key: LANGFLOW_WORKERS
        value: "1"
      - key: LANGFLOW_WORKER_TIMEOUT
        value: "120"

  - type: web
    name: langflow-frontend
    env: static
    buildCommand: cd src/frontend && npm ci && npm run build
    staticPublishPath: src/frontend/build
    envVars:
      - key: VITE_PROXY_TARGET
        value: https://langflow-backend.onrender.com
      - key: BACKEND_URL
        value: https://langflow-backend.onrender.com
    routes:
      - type: rewrite
        source: /api/*
        destination: https://langflow-backend.onrender.com/api/$1
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: langflow-database
    databaseName: langflow
    user: langflow
    plan: free
    postgresMajorVersion: 15