name = "langflow-frontend"
compatibility_date = "2024-01-01"

[env.production]
name = "langflow-frontend"

[[env.production.routes]]
pattern = "langflow.your-domain.com/*"
zone_name = "your-domain.com"
