name: langflow2.0
services:
- name: langflow-backend
  source_dir: /
  github:
    repo: ILYESS24/langflow2.0
    branch: main
  run_command: python start-simple.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /health
  envs:
  - key: PYTHON_VERSION
    value: "3.11.6"
  - key: LANGFLOW_SECRET_KEY
    value: "your-secret-key-change-in-production-12345"
  - key: LANGFLOW_SUPERUSER
    value: "admin"
  - key: LANGFLOW_SUPERUSER_PASSWORD
    value: "admin123"
  - key: LANGFLOW_AUTO_LOGIN
    value: "true"
  - key: LANGFLOW_BACKEND_ONLY
    value: "true"
  - key: LANGFLOW_CORS_ORIGINS
    value: "https://langflow-frontend.ondigitalocean.app"
  - key: LANGFLOW_LOG_LEVEL
    value: "INFO"
  - key: LANGFLOW_CACHE_TYPE
    value: "InMemoryCache"
  - key: LANGFLOW_WORKERS
    value: "1"
  - key: LANGFLOW_WORKER_TIMEOUT
    value: "120"

- name: langflow-frontend
  source_dir: src/frontend
  github:
    repo: ILYESS24/langflow2.0
    branch: main
  build_command: npm ci && npm run build
  run_command: npm run serve
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /api
    preserve_path_prefix: true
  envs:
  - key: VITE_PROXY_TARGET
    value: "https://langflow-backend.ondigitalocean.app"
  - key: BACKEND_URL
    value: "https://langflow-backend.ondigitalocean.app"

databases:
- name: langflow-database
  engine: PG
  version: "15"
  size: db-s-dev-database
  num_nodes: 1
