name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/frontend/package-lock.json
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install frontend dependencies
      working-directory: src/frontend
      run: npm ci
      
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
        
    - name: Run frontend tests
      working-directory: src/frontend
      run: npm run test:coverage
      
    - name: Run backend tests
      run: |
        python -m pytest src/backend/tests/ -v --cov=src --cov-report=xml
        
    - name: Build frontend
      working-directory: src/frontend
      run: npm run build
      
    - name: Deploy to Render
      run: |
        echo "🚀 Deployment to Render will be triggered automatically via Blueprint"
        echo "Repository: https://github.com/ILYESS24/langflow2.0"
        echo "Render will detect render.yaml and deploy automatically"
        
    - name: Notify deployment status
      run: |
        echo "✅ CI/CD Pipeline completed successfully!"
        echo "🌐 Your Langflow 2.0 will be available at:"
        echo "   Frontend: https://langflow-frontend.onrender.com"
        echo "   Backend: https://langflow-backend.onrender.com"
